version: "3"
services:
  
  mongo:
    image: mongo:4.4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - "/db-data:/data/db"
      - "/configs:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    ports:
      - 27017:${MONGO_PORT}